package main

var langText = map[string]map[string]string{
	"English": {
		"modeSelect": "Please select mode",
		"shortMode":  "Short Time High Frequency Breaks",
		"longMode":   "Long Time Low Frequency Breaks",
		"shortExplainText": "This mode is based on the 20-20-20 rule: every 20 minutes of screen time, look at something 20 feet (about 6 meters) away for 20 seconds to effectively relieve eye strain.\n\n" +
			"However, considering the time delay caused by clicking, this program adopts a mode of resting for 1 minute every 20 minutes, and a 5-minute break after every three 20-minute intervals.",
		"back":                    "Back",
		"next":                    "Next",
		"startStudyButton":        "Start Studying",
		"startRestButton":         "Start Resting",
		"countDown":               "Countdown",
		"Timing":                  "Timing...",
		"remain":                  "Remaining Time",
		"minute":                  "Minutes",
		"home":                    "Home",
		"every":                   "Every",
		"rest":                    "Rest",
		"restLabel":               "Time's up, take a break!",
		"studyStartNotifyTitle":   "Study Time",
		"studyStartNotifyContent": "Timer starts, let's work hard together!",
		"studyEndNotifyContent":   "Break time, let's start resting now!",
		"restStartNotifyTitle":    "Rest Time",
		"restStartNotifyContent":  "Break starts, remember to look at something 20 feet away for at least 20 seconds.",
		"restEndNotifyContent":    "Break's over, let's get back to studying!",
	},
	"简体中文": {
		"modeSelect": "请选择模式",
		"shortMode":  "短时间高频休息",
		"longMode":   "长时间低频休息",
		"shortExplainText": "此模式基于 20-20-20 规则：每使用屏幕 20 分钟，看向距离 20 英尺（约 6 米） 的物体 20 秒，可以有效缓解眼睛疲劳。\n\n" +
			"但是考虑到点击造成的时间延迟，本程序采用每 20 分钟休息 1 分钟的模式，同时每三个 20 分钟将进行 5 分钟的休息",
		"back":                    "返回",
		"next":                    "下一步",
		"startStudyButton":        "开始学习",
		"startRestButton":         "开始休息",
		"countDown":               "倒计时",
		"Timing":                  "计时中···",
		"remain":                  "剩余时间",
		"minute":                  "分钟",
		"home":                    "主界面",
		"every":                   "每",
		"rest":                    "休息",
		"restLabel":               "时间到，休息啦！",
		"studyStartNotifyTitle":   "学习时间",
		"studyStartNotifyContent": "开始计时，一起努力加油吧",
		"studyEndNotifyContent":   "休息时间到了，快点开始休息吧",
		"restStartNotifyTitle":    "休息时间",
		"restStartNotifyContent":  "开始休息，记得向 6 米外的地方至少看 20 秒哦",
		"restEndNotifyContent":    "休息结束，继续一起努力学习吧",
	},
	"日本語": {
		"modeSelect": "モードを選択してください",
		"shortMode":  "短時間高頻度休憩",
		"longMode":   "長時間低頻度休憩",
		"shortExplainText": "このモードは20-20-20ルールに基づいています：スクリーンを20分使用するごとに、20フィート（約6メートル）離れた物を見ることで目の疲れを緩和できます。\n\n" +
			"クリックによる時間遅延を考慮して、このプログラムは20分ごとに1分の休憩を取り、さらに3回の20分ごとに5分の休憩を取ります",
		"back":                    "戻る",
		"next":                    "次へ",
		"startStudyButton":        "勉強を始めましょう",
		"startRestButton":         "休憩を始めましょう",
		"countDown":               "カウントダウン",
		"Timing":                  "計時中...",
		"remain":                  "残り時間",
		"minute":                  "分",
		"home":                    "ホーム画面",
		"every":                   "毎",
		"rest":                    "休憩",
		"restLabel":               "休みしましょう",
		"studyStartNotifyTitle":   "勉強時間",
		"studyStartNotifyContent": "タイマー開始、一緒に頑張りましょう",
		"studyEndNotifyContent":   "休憩時間です、すぐに休憩を始めましょう",
		"restStartNotifyTitle":    "休憩時間",
		"restStartNotifyContent":  "休憩開始、6メートル離れた場所を見るのを忘れないでください",
		"restEndNotifyContent":    "休憩終了、また一緒に勉強を頑張りましょう",
	},
}

func GetText(language string, key string) string {
	return langText[language][key]
}
